config/routes.rb
Rails.application.routes.draw do
  get 'extratos/index'
  root 'home#index'

  devise_for :clientes, controllers: {
    registrations: 'clientes/registrations',
    sessions: 'clientes/sessions'
  }

  resources :depositos, only: %i[show new create]
  resources :contas, only: %i[show new create edit update] do
    member do
      get 'extrato'
    end
  end
  resources :saques, only: %i[show new create]
  resources :transferencias, only: %i[show new create]
end

app/models/transferencia.rb
# == Schema Information
#
# Table name: transferencias
#
#  id               :bigint           not null, primary key
#  valor            :decimal(, )
#  conta_origem_id  :bigint
#  conta_destino_id :bigint
#  taxa             :decimal(, )
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Transferencia < ApplicationRecord
  belongs_to :conta_origem, class_name: "Conta"
  belongs_to :conta_destino, class_name: "Conta"

  before_save :transferir

  validates :conta_origem, :conta_destino, :valor, presence: true
  validates :valor, numericality: { greater_than: 0 }

  def transferir
    ActiveRecord::Base.transaction do
      taxa_transferencia
      valida_saldo_suficiente

      self.conta_destino.saldo += self.valor
      self.conta_destino.save!
      self.conta_origem.saldo -= (self.valor + self.taxa)
      self.conta_origem.save!
    end
  end

  private

  # Taxa de transferência:
  # De segunda a sexta das 9 às 18 horas a taxa é 5 reais por transferência
  # Fora desse horário a taxa é 7 reais
  # Acima de 1000 reais há um adicional de 10 reais na taxa
  def taxa_transferencia
    self.taxa = 0
    hora_util = DateTime.now.hour >= 9 and DateTime.now.hour <= 18
    dia_util  = DateTime.now.wday < 6 and DateTime.now.wday > 0

    if hora_util and dia_util
      self.taxa = 5
    else
      self.taxa = 7
    end

    self.taxa += 10 if self.valor > 1000
  end

  # Refatorar esse método e levá-lo para Model Conta
  def valida_saldo_suficiente
    unless self.conta_origem.saldo >= self.valor + self.taxa
      errors.add(:valor, 'Saldo insuficiente!')
      return
    end
  end
end

app/controllers/transferencias_controller.rb
# == Schema Information
#
# Table name: transferencias
#
#  id               :bigint           not null, primary key
#  valor            :decimal(, )
#  conta_origem_id  :bigint
#  conta_destino_id :bigint
#  taxa             :decimal(, )
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class TransferenciasController < ApplicationController
  before_action :set_transferencia, only: [:show]

  def show
  end

  def new
    @transferencia = Transferencia.new
    @conta         = current_cliente.conta
  end

  def create
    @transferencia = Transferencia.new(transferencia_params)

    respond_to do |format|
      if @transferencia.save
        format.html { redirect_to conta_path(current_cliente.conta), notice: 'Transferência realizada com sucesso!.' }
      else
        format.html { render :new }
      end
    end
  end

  private

  def set_transferencia
    @transferencia = Transferencia.find(params[:id])
  end

  def transferencia_params
    params.require(:transferencia).permit(:valor, :conta_origem_id, :conta_destino_id, :taxa)
  end
end

app/helpers/transferencias_helper.rb
# == Schema Information
#
# Table name: transferencias
#
#  id               :bigint           not null, primary key
#  valor            :decimal(, )
#  conta_origem_id  :bigint
#  conta_destino_id :bigint
#  taxa             :decimal(, )
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
module TransferenciasHelper
end

app/views/transferencias/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@transferencia, html: { class: 'col s12' }) do |f|
  %span.orange-text.darken-4
    = f.error_notification
    = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .row
    .input-field.col.s12
      = f.input :valor, input_html: { placeholder: 'Valor em R$' }
  .row
    .input-field.col.s12.m6
      = f.association :conta_origem, collection: [current_cliente.conta],
        label_method: :numero, value_method: :id,
        selected: current_cliente.conta
    .input-field.col.s12.m6
      = f.association :conta_destino, collection: Conta.where.not(cliente: current_cliente),
        label_method: :numero, value_method: :id,
        include_blank: 'Selecione a Conta de Destino'
  .row
    .input-field.col.s12.m6
      = f.input :taxa, as: :hidden
  .row
    = link_to 'voltar', conta_path(current_cliente.conta), class: 'btn'
    = f.button :submit, 'Transferir valor'

app/views/transferencias/new.html.erb
<h1>Nova Transferência</h1>
<%= render 'form' %>

app/views/transferencias/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<p>
  <b>Valor:</b>
  <%= @transferencia.valor %>
</p>
<p>
  <b>Conta origem:</b>
  <%= @transferencia.conta_origem %>
</p>
<p>
  <b>Conta destino:</b>
  <%= @transferencia.conta_destino %>
</p>
<p>
  <b>Taxa:</b>
  <%= @transferencia.taxa %>
</p>
<%= link_to 'Edit', edit_transferencia_path(@transferencia) %>
\|
<%= link_to 'Back', transferencias_path %>