config/routes.rb
Rails.application.routes.draw do
  get 'extratos/index'
  root 'home#index'

  devise_for :clientes, controllers: {
    registrations: 'clientes/registrations',
    sessions: 'clientes/sessions'
  }

  resources :depositos, only: %i[show new create]
  resources :contas, only: %i[show new create edit update] do
    member do
      get 'extrato'
    end
  end
  resources :saques, only: %i[show new create]
  resources :transferencias, only: %i[show new create]
end

app/models/conta.rb
# == Schema Information
#
# Table name: contas
#
#  id         :bigint           not null, primary key
#  cliente_id :bigint           not null
#  saldo      :decimal(, )      default(0.0)
#  agencia    :string           default("100")
#  numero     :string           default("0001")
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  deleted_at :datetime
#
class Conta < ApplicationRecord
  belongs_to :cliente, dependent: :destroy, optional: true
  
  acts_as_paranoid

  after_update :encerrar

  validates :saldo, numericality: { greater_than_or_equal_to: 0 }
  validates :agencia, :numero, :status, presence: true


  enum status: {
    aberta: 0,
    encerrar: 1
  }

  def encerrar
    self.destroy if self.encerrar?
  end

  def depositos
    Deposito.find_by(numero_conta: self.numero)
  end

  def extrato dt_inicial, dt_final
    if dt_inicial.present? and dt_final.present?
      @extratos = []
      @extratos << Deposito.where(created_at: dt_inicial.to_date.beginning_of_day..dt_final.to_date.end_of_day, numero_conta: self.numero)
                           .order(created_at: :asc)
      @extratos << Saque.where(created_at: dt_inicial.to_date.beginning_of_day..dt_final.to_date.end_of_day, conta: self)
                        .order(created_at: :asc)
      @extratos << Transferencia.where(created_at: dt_inicial.to_date.beginning_of_day..dt_final.to_date.end_of_day, conta_origem: self)
                                .order(created_at: :asc)
      @extratos.flatten!
    end
  end
end

app/controllers/contas_controller.rb
# == Schema Information
#
# Table name: contas
#
#  id         :bigint           not null, primary key
#  cliente_id :bigint           not null
#  saldo      :decimal(, )      default(0.0)
#  agencia    :string           default("100")
#  numero     :string           default("0001")
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  deleted_at :datetime
#
class ContasController < ApplicationController
  include ContasHelper

  before_action :set_conta, only: [:show, :edit, :update, :extrato]
  skip_before_action :authenticate_cliente!, only: [:new, :create]

  def show
  end

  def new
    @conta = Conta.new
  end

  def edit
  end

  def create
    @conta = Conta.new(conta_params)

    respond_to do |format|
      if @conta.save
        format.html { redirect_to @conta, notice: 'Conta was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @conta.update(conta_params)
        msg = @conta.encerrar? ? 'Conta encerrada com sucesso!' : 'Selecione a opção encerrar'
        format.html { redirect_to @conta, notice: msg }
      else
        format.html { render :edit }
      end
    end
  end

  def extrato
    if params[:search] and params[:search][:dt_inicial] and params[:search][:dt_final]
        @extratos = @conta.extrato(params[:search][:dt_inicial], params[:search][:dt_final])
    end

    respond_to do |format|
      format.js { render layout: false }
    end
  end

  private

  def set_conta
    @conta = Conta.find(params[:id])
  end

  def conta_params
    params.require(:conta).permit(:cliente_id, :saldo, :agencia, :numero, :status)
  end
end

app/helpers/contas_helper.rb
# == Schema Information
#
# Table name: contas
#
#  id         :bigint           not null, primary key
#  cliente_id :bigint           not null
#  saldo      :decimal(, )      default(0.0)
#  agencia    :string           default("100")
#  numero     :string           default("0001")
#  status     :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  deleted_at :datetime
#
module ContasHelper

  def deposito_or_extrato extrato
    extrato.class == Deposito ? '' : 'red-text text-darken-2'
  end

  def sinal extrato
    extrato.class == Deposito ? '+' : '-'
  end

end

app/views/contas/_extrato.html.haml
- if extratos.present?
  .col.s12
    %table.responsive-table.centered
      %thead
        %tr
          %th Tipo
          %th Valor
          %th Data
      %tbody
        - extratos.each do |extrato|
          %tr{class: "#{deposito_or_extrato(extrato)}"}
            %td=extrato.class
            %td="#{sinal(extrato)} #{number_to_currency(extrato.valor)}"
            %td=extrato.created_at.strftime('%d/%m/%Y')
- else
  %p Sem lançamentos!

app/views/contas/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@conta) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    -# = f.association :cliente
    = f.input :saldo, input_html: {readonly: true}
    = f.input :agencia, readonly: true
    = f.input :numero, readonly: true
    = f.input :status, label: false, collection: Conta.status.keys, prompt: 'Mudar status', input_html: {id: 'status'}

  .form-actions
    = f.button :submit, 'Atualizar'

app/views/contas/edit.html.haml
%h1 Editar conta

= render 'form'

-# = link_to 'Show', @conta
-# \|
-# = link_to 'Back', contas_path

app/views/contas/extrato.js.haml
$("#extrato").html("#{escape_javascript(render partial: 'contas/extrato', locals: { extratos: @extratos } )}");

app/views/contas/new.html.haml
%h1 Nova Conta

= render 'form'

app/views/contas/show.html.erb
<div class="row">
  <div class="col s12">
    <h4>
      <%= "Conta Corrente - #{@conta.numero}" %>
    </h4>
  </div>
</div>
<div class="row">
  <div class="col s12 m12 l4">
    <ul class="collapsible">
      <li>
        <div class="collapsible-header">
          <i class="material-icons">attach_money</i>
          Mostrar Saldo
        </div>
        <div class="collapsible-body">
          <div class="row">
            <div class="col s12">
              <h5>
                <%= number_to_currency(@conta.saldo) %>
              </h5>
            </div>
          </div>
        </div>
      </li>
    </ul>
  </div>
  <div class="col s12 m12 l8">
    <ul class="collapsible">
      <li>
        <div class="collapsible-header">
          <i class="material-icons">account_balance</i>
          Extrato
        </div>
        <div class="collapsible-body">
          <div class="row">
            <%= simple_form_for :search, url: extrato_conta_path, method: :get, remote: true, html: {class: 'col s12'} do |f| %>
              <div class="row">
                <div class="input-field col s4">
                  <%= f.input :dt_inicial, label: false, input_html: { placeholder: 'Data Inicial', class: 'datepicker' } %>
                </div>
                <div class="input-field col s4">
                  <%= f.input :dt_final, label: false, input_html: { placeholder: 'Data Final', class: 'datepicker' } %>
                </div>
                <div class="col s3 valign-wrapper">
                  <button class="btn btn-large waves-effect waves-light" name="action" type="submit">Extrato</button>
                </div>
              </div>
            <% end %>
          </div>
          <div class="row">
            <div id="extrato"></div>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>