config/routes.rb
Rails.application.routes.draw do
  get 'extratos/index'
  root 'home#index'

  devise_for :clientes, controllers: {
    registrations: 'clientes/registrations',
    sessions: 'clientes/sessions'
  }

  resources :depositos, only: %i[show new create]
  resources :contas, only: %i[show new create edit update] do
    member do
      get 'extrato'
    end
  end
  resources :saques, only: %i[show new create]
  resources :transferencias, only: %i[show new create]
end

app/models/saque.rb
# == Schema Information
#
# Table name: saques
#
#  id         :bigint           not null, primary key
#  valor      :decimal(, )
#  conta_id   :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Saque < ApplicationRecord
  belongs_to :conta

  before_save :sacar

  validates :valor, numericality: { greater_than: 0 }, presence: true
  validate :valida_saldo_suficiente
  validates :conta, presence: true

  def sacar
    ActiveRecord::Base.transaction do
      conta = self.conta
      conta.saldo -= self.valor 
      conta.save!
    end
  end

  private

  def valida_saldo_suficiente
    if self.conta and self.valor
      errors.add(:valor, 'Saldo insuficiente para este valor') unless self.conta.saldo >= self.valor
    end
  end
end

app/controllers/saques_controller.rb
# == Schema Information
#
# Table name: saques
#
#  id         :bigint           not null, primary key
#  valor      :decimal(, )
#  conta_id   :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class SaquesController < ApplicationController
  before_action :set_saque, only: [:show]

  def show
  end

  def new
    @saque = Saque.new
  end

  def create
    @saque = Saque.new(saque_params)

    respond_to do |format|
      if @saque.save
        format.html { redirect_to conta_path(@saque.conta), notice: 'Saque realizado com sucesso!' }
      else
        format.html { render :new }
      end
    end
  end

  private

  def set_saque
    @saque = Saque.find(params[:id])
  end

  def saque_params
    params.require(:saque).permit(:valor, :conta_id)
  end
end

app/helpers/saques_helper.rb
# == Schema Information
#
# Table name: saques
#
#  id         :bigint           not null, primary key
#  valor      :decimal(, )
#  conta_id   :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
module SaquesHelper
end

app/views/saques/_form.html.erb
<% # frozen_string_literal: true %>
<%= simple_form_for(@saque, html: {class: 'row'}) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="row">
    <div class="col s12 m6 l6">
      <%= f.association :conta, collection: [current_cliente.conta], label_method: :numero, value_method: :id, include_blank: 'Selecione sua conta' %>
    </div>
    <div class="col s12 m6 l6">
      <%= f.input :valor %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= link_to 'voltar', conta_path(current_cliente.conta), class: 'btn' %>
      <%= f.button :submit, 'Sacar valor' %>
    </div>
  </div>
<% end %>

app/views/saques/new.html.erb
<h1>Novo Saque</h1>
<%= render 'form' %>

app/views/saques/show.html.erb
<p id="notice">
  <%= notice %>
</p>
<p>
  <b>Valor:</b>
  <%= @saque.valor %>
</p>
<p>
  <b>Conta:</b>
  <%= @saque.conta %>
</p>
<%= link_to 'Edit', edit_saque_path(@saque) %>
\|
<%= link_to 'Back', saques_path %>