config/routes.rb
Rails.application.routes.draw do
  get 'extratos/index'
  root 'home#index'

  devise_for :clientes, controllers: {
    registrations: 'clientes/registrations',
    sessions: 'clientes/sessions'
  }

  resources :depositos, only: %i[show new create]
  resources :contas, only: %i[show new create edit update] do
    member do
      get 'extrato'
    end
  end
  resources :saques, only: %i[show new create]
  resources :transferencias, only: %i[show new create]
end

app/views/layouts/_alerts.html.haml
- flash.each do |type, message|
  = javascript_tag "M.toast({html: '#{message}'}, 4000)"

app/views/layouts/_navbar.html.erb
<nav style="background: orangered; position: relative; margin-bottom: 150px;">
  <div class="container">
    <div class="nav-wrapper">
      <%= link_to 'Nobe Digital', root_path, class: 'brand-logo' %>
      <ul class="right hide-on-med-and-down" id="nav-mobile">
        <% if cliente_signed_in? %>
          <li>
            <a class="dropdown-trigger" data-target="dropdown1" href="#!">
              Conta
              <i class="material-icons right">arrow_drop_down</i>
            </a>
          </li>
          <li>
            <%= link_to destroy_cliente_session_path, method: :delete, title: 'Sair' do %>
              <i class="material-icons left">exit_to_app</i>
              Sair
            <% end %>
          </li>
        <% else %>
          <li>
            <%= link_to new_cliente_session_path do %>
              <i class="material-icons left">lock</i>
              Entrar
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

<% if cliente_signed_in? %>
  <ul class="dropdown-content" id="dropdown1">
    <li>
      <%= link_to 'Minha Conta', conta_path(current_cliente.conta) %>
    </li>
    <li>
      <%= link_to 'Saque', new_saque_path %>
    </li>
    <li>
      <%= link_to 'Depósito', new_deposito_path %>
    </li>
    <li>
      <%= link_to 'Transferência', new_transferencia_path %>
    </li>
    <li class="divider" tabindex="-1">
      <li>
        <%= link_to 'Encerrar', edit_conta_path(current_cliente.conta) %>
      </li>
    </li>
  </ul>
<% end %>

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %link{:href => "https://fonts.googleapis.com/icon?family=Material+Icons", :rel => "stylesheet"}/

    %title Conta Bancaria
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    
  %body
    = render 'layouts/navbar'
    .container
      = render 'layouts/alerts'
      %br
      = yield